# -*- coding: utf-8 -*-
"""agentfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ar82am7k5WO6sxDpjWMK_v0ydGTXumv7
"""

from google.colab import drive
drive.mount("/content/drive")

import os

BASE_DIR = "/content/drive/MyDrive/imar_rag"
RAW_DIR = os.path.join(BASE_DIR, "data/raw")
os.makedirs(RAW_DIR, exist_ok=True)

print("📁 Klasör hazır:", RAW_DIR)

!pip install pymupdf

import fitz  # PyMuPDF

pdf_path = "/content/drive/MyDrive/imar_rag/data/raw/planli-20210811131259.pdf"
output_path = "/content/drive/MyDrive/imar_rag/data/planli_alanlar_imar_yonetmeligi.txt"

doc = fitz.open(pdf_path)

all_text = []

for page_num, page in enumerate(doc):
    text = page.get_text()
    all_text.append(f"\n--- SAYFA {page_num + 1} ---\n")
    all_text.append(text)

doc.close()

with open(output_path, "w", encoding="utf-8") as f:
    f.write("\n".join(all_text))

print("✅ PDF metne çevrildi:", output_path)

import os
import json

BASE_DIR = "/content/drive/MyDrive/imar_rag/data"

txt_path = os.path.join(BASE_DIR, "planli_alanlar_imar_yonetmeligi.txt")
output_path = os.path.join(BASE_DIR, "chunks.jsonl")

chunk_size = 800
overlap = 150

with open(txt_path, "r", encoding="utf-8") as f:
    text = f.read()

chunks = []
start = 0
chunk_id = 0

while start < len(text):
    end = start + chunk_size
    chunk_text = text[start:end]

    chunks.append({
        "chunk_id": chunk_id,
        "text": chunk_text
    })

    chunk_id += 1
    start = end - overlap

with open(output_path, "w", encoding="utf-8") as f:
    for chunk in chunks:
        f.write(json.dumps(chunk, ensure_ascii=False) + "\n")

print(f"✅ {len(chunks)} adet chunk oluşturuldu")
print("📄 Kaydedildi:", output_path)

!pip install chromadb sentence-transformers

from chromadb.utils import embedding_functions

import json
import os
import chromadb
from sentence_transformers import SentenceTransformer

BASE_DIR = "/content/drive/MyDrive/imar_rag/data"
chunks_path = f"{BASE_DIR}/chunks.jsonl"
chroma_path = f"{BASE_DIR}/chroma_final"

os.makedirs(chroma_path, exist_ok=True)

# 🔴 Embedding'i BİZ üretiyoruz
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

documents = []
embeddings = []
ids = []

with open(chunks_path, "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)
        text = item["text"]
        documents.append(text)
        embeddings.append(model.encode(text))
        ids.append(str(item["chunk_id"]))

print("✅ Embedding üretildi:", len(embeddings))

client = chromadb.PersistentClient(path=chroma_path)

collection = client.get_or_create_collection(
    name="imar_yonetmeligi_manual"
)

collection.add(
    documents=documents,
    embeddings=embeddings,  # 🔴 KRİTİK
    ids=ids
)

print("✅ Chroma'ya yazıldı")
print("📦 count:", collection.count())

!ls /content/drive/MyDrive/imar_rag/data/chroma_final

collection.count()

!pip install groq
import groq

print(groq.__version__)

from google.colab import userdata
from groq import Groq

groq_api_key = userdata.get('GROQ_API_KEY')
groq_client = Groq(api_key=groq_api_key)

chat_completion = groq_client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {"role": "user", "content": "Merhaba, çalışıyor musun?"}
    ]
)

print(chat_completion.choices[0].message.content)

!pip install yfinance
import re
import math
import yfinance as yf
from collections import Counter

# 2. RAG MOTORU (In-Memory Vector Store)
# ------------------------------------------------------------------


class SimpleRAG:
    def __init__(self):
        self.vector_store = []

    def get_embedding(self, text):
        words = re.findall(r'\w+', text.lower())
        return Counter(words)

    def _cosine_similarity(self, vec1, vec2):
        intersection = set(vec1.keys()) & set(vec2.keys())
        numerator = sum([vec1[x] * vec2[x] for x in intersection])
        sum1 = sum([vec1[x]**2 for x in vec1.keys()])
        sum2 = sum([vec2[x]**2 for x in vec2.keys()])
        denominator = math.sqrt(sum1) * math.sqrt(sum2)
        return float(numerator) / denominator if denominator else 0.0

    def ingest(self, text):
        chunks = [s.strip() for s in text.split('.') if s.strip()]
        for chunk in chunks:
            self.vector_store.append({
                "content": chunk,
                "vector": self.get_embedding(chunk)
            })

    def retrieve(self, query, top_k=2):
        query_vec = self.get_embedding(query)
        scores = []
        for item in self.vector_store:
            score = self._cosine_similarity(query_vec, item["vector"])
            scores.append((score, item["content"]))
        scores.sort(key=lambda x: x[0], reverse=True)
        return "\n".join([item[1] for item in scores[:top_k] if item[0] > 0])

# RAG Data Ingestion
rag_engine = SimpleRAG()
mock_data = """
TechCorp employees are allowed to work remotely for 3 days a week.
Lunch is provided for free at the office, and no meal card is given.
TechCorp annual leave entitlement is 14 days for the first year.
Performance bonuses are distributed at the end of each quarter based on EBITDA targets.
"""
rag_engine.ingest(mock_data)

import requests
from bs4 import BeautifulSoup

def web_search_tool(query: str) -> str:
    """
    Use this tool to search the internet for up-to-date or external information.
    Returns a short textual summary from the web.
    """
    print(f"\n🌐 [WEB SEARCH] Searching the web for: '{query}'")

    url = f"https://duckduckgo.com/html/?q={query}"
    response = requests.get(url, headers={"User-Agent": "Mozilla/5.0"})

    if response.status_code != 200:
        return "Web search failed."

    soup = BeautifulSoup(response.text, "html.parser")
    results = soup.find_all("a", class_="result__a")

    snippets = []
    for r in results[:3]:
        snippets.append(r.get_text())

    return " | ".join(snippets) if snippets else "No web results found."

# 3. ARAÇLAR (TOOLS) - DOCSTRINGS EKLENDİ (KRİTİK)
# ------------------------------------------------------------------
import yfinance as yf

def calculator(expression: str) -> str:
    """
    Calculates the result of a mathematical expression.
    e.g. calculator: 100 * 0.15
    """
    try:
        allowed_chars = set("0123456789+-*/(). ")
        if not all(c in allowed_chars for c in expression):
            return "Error: Invalid characters."
        return str(eval(expression))
    except Exception as e:
        return f"Error: {e}"

import chromadb
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

CHROMA_PATH = "/content/drive/MyDrive/imar_rag/data/chroma_final"
client = chromadb.PersistentClient(path=CHROMA_PATH)
collection = client.get_collection(name="imar_yonetmeligi_manual")

def search_knowledge_base(query: str) -> str:
    """
    Use this tool to search the Imar Yonetmeligi knowledge base.
    Returns raw regulation text (context only).
    """
    print(f"\n🔍 [IMAR RAG] Searching for: '{query}'")

    query_vec = embedding_model.encode(query).tolist()

    results = collection.query(
        query_embeddings=[query_vec],
        n_results=3
    )

    contexts = results["documents"][0]

    if not contexts:
        return "No relevant regulation text found."

    return "\n".join(contexts)


def company_address(ticker: str)-> str:
    """
    Returns company address for input ticker.
    e.g. company_address: AAPL
    Returns company address for ticker AAPL which is stock ticker for Apple Inc.
    """
    ticker_obj = yf.Ticker(ticker)
    info = ticker_obj.get_info()

    return " ".join([info[key] for key in ["address1", "city", "state", "zip", "country"]])

def fulltime_employees(ticker: str)-> int:
    """
    Returns fulltime employees count for input ticker.
    e.g. fulltime_employees: MSFT
    Returns fulltime employees count for ticker MSFT which is stock ticker for Microsoft.
    """
    ticker_obj = yf.Ticker(ticker)
    info = ticker_obj.get_info()

    return info["fullTimeEmployees"]


def last_close_price(ticker: str)-> float:
    """
    Returns last close price for input ticker.
    e.g. last_close_price: MSFT
    Returns latest close price for ticker MSFT which is stock ticker for Microsoft.
    """
    ticker_obj = yf.Ticker(ticker)
    info = ticker_obj.get_info()

    return info["previousClose"]

def EBITDA(ticker: str)-> float:
    """
    Returns EBITDA for input ticker.
    e.g. EBITDA: AAPL
    Returns EBITDA for ticker AAPL which is stock ticker for Apple.
    """
    ticker_obj = yf.Ticker(ticker)
    info = ticker_obj.get_info()

    return info["ebitda"]

def total_debt(ticker: str)-> float:
    """
    Returns total debt for input ticker.
    e.g. total_debt: AAPL
    Returns total debt for ticker AAPL which is stock ticker for Apple.
    """
    ticker_obj = yf.Ticker(ticker)
    info = ticker_obj.get_info()

    return info["totalDebt"]

def total_revenue(ticker: str)-> float:
    """
    Returns total revenue for input ticker.
    e.g. total_revenue: MSFT
    Returns total revenue for ticker MSFT which is stock ticker for Microsoft.
    """
    ticker_obj = yf.Ticker(ticker)
    info = ticker_obj.get_info()

    return info["totalRevenue"]

def debt_to_equity_ratio(ticker: str)-> float:
    """
    Returns debt to equity ratio for input ticker.
    e.g. debt_to_equity_ratio: AAPL
    Returns debt to equity ratio for ticker AAPL which is stock ticker for Apple.
    """
    ticker_obj = yf.Ticker(ticker)
    info = ticker_obj.get_info()

    return info["debtToEquity"]
# Tool List
tools = [calculator, search_knowledge_base, web_search_tool, company_address, fulltime_employees, last_close_price, EBITDA, total_debt, total_revenue]

tools_with_desc = "\n\n".join([tool.__name__ + tool.__doc__ for tool in tools])

print(tools_with_desc)

known_actions = dict([(tool.__name__, tool) for tool in tools])
known_actions

system_prompt = f"""
You run in a loop of Thought, Action, PAUSE, Observation.
At the end of the loop you output an Answer.

GUIDELINES:
1. Use 'search_knowledge_base' for questions related to Imar Yonetmeligi, zoning rules, construction regulations, emsal, kat sayisi, bina kosullari.
2. Use other tools (yfinance) for public stock market data.
3. Use 'calculator' for ANY math calculation. DO NOT calculate in your head.
4. Use Thought to describe your routing decision.
5. When you have enough information to answer the question, you MUST produce a line starting with "Answer:" and stop.
6. Use 'web_search_tool' ONLY when information is not available in the Imar Yonetmeligi or requires current/external knowledge.
7. If a question mentions a specific year (e.g. 2024), current events, laws, government decisions, or amnesty (imar affı),
you MUST use web_search_tool as the FIRST action.
Do NOT use search_knowledge_base before web_search_tool in such cases.
8. All answers must be in Turkish.

Your available actions are:

{tools_with_desc}

Example session:

Question: What is half of Apple's last close price?
Thought: I need to get the price first, then divide by 2 using calculator.
Action: last_close_price: AAPL
PAUSE
Observation: 220.0
Thought: Now I need to calculate half of 220.0
Action: calculator: 220.0 / 2
PAUSE
Observation: 110.0
Answer: Half of Apple's last close price is 110.0 USD.
""".strip()
class Agent:
    def __init__(self, system=""):
        self.system = system

    def __call__(self, message):
        return self.execute(message)

    def execute(self, message):
        messages = [
            {"role": "system", "content": self.system},
            {"role": "user", "content": message}
        ]

        result = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=messages,
            temperature=0,
            max_tokens=512,          # 🔥 önemli
            stop=["<|"]
        )

        return result.choices[0].message.content

agent = Agent(system_prompt)
agent("Konut alanlarında emsal nasıl hesaplanır?")

obs = search_knowledge_base("Konut alanlarında emsal hesaplanması")
print(obs)

final_answer = agent.execute()
print(final_answer)

# 5. ORKESTRASYON DÖNGÜSÜ (FINAL)
# ------------------------------------------------------------------
import re

action_re = re.compile(r'^Action: (\w+): (.*)$')

def query(question, max_turns=10):
    i = 0
    react_agent = Agent(system_prompt)
    next_prompt = question
    used_actions = set()   # 🔒 Loop prevention

    print(f"\n{'='*40}\nQUESTION: {question}\n{'='*40}")

    while i < max_turns:
        i += 1

        result = react_agent(next_prompt)
        print(f"\033[94m{result}\033[0m")

        actions = [action_re.match(a) for a in result.split('\n') if action_re.match(a)]

        if actions:
            action, action_input = actions[0].groups()

            if action not in known_actions:
                raise Exception(f"Unknown action: {action}: {action_input}")

            # 🔁 Aynı tool tekrar çağrılmasın
            if action in used_actions:
                print(f"=> {action} already used, skipping to prevent loop")
                next_prompt = (
                    "Observation: This tool was already used and did not provide new information. "
                    "Use existing observations to answer the question."
                )
                continue

            used_actions.add(action)

            print(f"=> Running {action} with input: {action_input}")

            try:
                observation = known_actions[action](action_input)
            except Exception as e:
                observation = f"Error executing tool: {e}"

            print(f"Observation: {observation}")
            next_prompt = f"Observation: {observation}"

        else:
            if "Answer:" in result:
                print("\n\033[92m--- FINAL ANSWER FOUND ---\033[0m")
                print(result.split("Answer:")[-1].strip())
            return

query("Konut alanlarında emsal nasıl hesaplanır?")

query("1000 m² arsada emsal 1.50 ise maksimum inşaat alanı kaç m²’dir?")

query("2024 yılında Türkiye’de imar affı var mı ve emsal hesabını etkiler mi?")

query("İmar affı kapsamına giren yapıların, sonradan yapılacak yeni inşaatlarda emsal (KAKS) hesabına etkisi olur mu?")

query("""
İmar yönetmeliğine göre konut alanlarında emsal (KAKS) hesabı nasıl tanımlanır?

İstanbul için güncel dolar/TL kurunu web üzerinden öğren.
Ardından 800 m² büyüklüğünde bir parsel için,
emsal (KAKS) değeri 1.25 olan bir imar parselinde
maksimum inşaat alanını hesapla.

Son olarak, bulunan maksimum inşaat alanının
1 m² inşaat maliyeti 900 USD kabul edilirse,
toplam inşaat maliyetini TL cinsinden hesapla.

""")

query("3194 sayılı İmar Kanunu’nun 18. maddesi uygulamasıyla arazi ve arsa düzenlemesi yapılırken, mal sahiplerinin arsalarından en fazla yüzde kaç oranında alan kamu kullanımına ayrılabilir?")
query("Köy yerleşik alanı içinde, köy nüfusuna kayıtlı kişiler kendi ihtiyaçları için en fazla kaç katlı konutları yapı ruhsatı almadan inşa edebilir?")
query("İmar planı bulunmayan bir tarlaya veya araziye yasal olarak bina yapabilmek için öncelikle ne yapılmalıdır?")
query("Büyükşehir belediyesi olan illerde 1/5000 ölçekli nazım imar planını onaylama yetkisi kimdedir? 1/1000 ölçekli uygulama imar planını onaylama yetkisi kimdedir?")
query("Bir Organize Sanayi Bölgesi (OSB) içerisindeki imar planlarını hangi kurum onaylar? OSB içindeki yapı ruhsatlarını verme yetkisi kimdedir?")

query("Kültür ve Turizm Koruma ve Gelişim Bölgesi ilan edilmiş bir alanda imar planlarını yapma ve onaylama yetkisi hangi bakanlığa aittir?")
query("1/5000 ölçekli nazım imar planı ile 1/1000 ölçekli uygulama imar planı arasında içerik ve amaç bakımından ne fark vardır?")
query("Nazım imar planı ile uygulama imar planı arasında bir çelişki ortaya çıkarsa, plan uygulamalarında hangisi esas alınır? Bu durumda ne yapılması gerekir?")
query("Kadastro parseli ile imar parseli kavramları ne anlama gelir? Aralarındaki fark nedir?")
query("Planlı bir alanda bir parselin ifraz (ayrılıp küçültülmesi) yapılarak yeni parseller oluşturulabilmesi için hangi şartların sağlanması gerekir?")

query("İmar planında arsası 'park alanı' olarak ayrılan bir kişi, arsasına bina yapabilir mi? Bu durumda arsa sahibi hangi haklara sahiptir veya ne talep edebilir?")
query("Yapı ruhsatı ile yapı kullanma izni (iskan) arasındaki fark nedir? Bir binada iskan izni olmadan kullanıma geçilirse ne tür sorunlar ortaya çıkar?")
query("Onaylı imar planlarında değişiklik (plan tadilatı) yapmak için izlenen süreç nasıldır? Plan değişikliği taleplerini kimler, nasıl teklif edebilir?")
query("Ruhsatsız veya imara aykırı (kaçak) yapı tespit edildiğinde belediye tarafından hangi işlemler uygulanır? Kaçak yapı sahibini ne gibi yaptırımlar bekler?")
query("Temel gerektirmeyen prefabrik veya konteyner yapılar, imar mevzuatına göre yapı ruhsatı gerektirir mi? Bu tür yapılar için izin alınması gerekir mi?")

query("Bir parselde imar yönetmeliğine göre gerekli otopark alanı parselde sağlanamıyorsa, bu sorunu çözmek için mevzuatta öngörülen yöntem nedir?")
query("Tescilli bir tarihi yapıda (korunması gerekli kültür varlığı) restorasyon veya tadilat yapmak için hangi kuruldan onay almak gerekir?")
query("Kentsel sit alanlarında yapılacak yeni yapı ve düzenlemeler hangi tür imar planına göre gerçekleştirilir ve bu planlar kimlerin onayına tabidir?")
query("Kentsel tasarım projesi nedir? Bir kentsel tasarım projesinin imar planından farkı nedir; imar planı yerine geçer mi?")
query("6306 sayılı Kanun kapsamında bir binanın 'riskli yapı' olarak tespit edilmesi nasıl yapılır ve bu tespit yapıldığında bina sahibi açısından süreç nasıl devam eder?")

query("Afet riski altındaki alanların dönüştürülmesi hakkında 6306 sayılı Kanun uyarınca 'riskli alan' ilan edilen bir bölgede imar planları kimin tarafından hazırlanır ve onaylanır? Bu alanlarda planlama süreci nasıldır?")
query("2018 yılında getirilen 'imar barışı' düzenlemesi kapsamında verilen Yapı Kayıt Belgesi bir yapıya hangi hakları sağlar? Hangi durumlarda yeni imar hakkı getirmez?")
query("Kıyı Kanunu’na göre deniz kıyısında, kıyı kenar çizgisinden itibaren kaç metrelik alan yapılaşmaya tamamen kapalıdır? Kıyı bölgesinin ikinci 50 metrelik kısmında hangi tür kullanımlara izin verilebilir?")
query("Bir parselin imar planında 'TAKS=0.30, KAKS=1.20, Hmax=15 m, 4 kat' şeklinde belirtilen yapılaşma koşulları o parselde yapılabilecek bina için ne anlama gelir? Bu değerler bina yüksekliği ve kat adedi açısından nasıl uygulanır?")
query("İmar planlarında sosyal ve teknik altyapı (donatı) alanlarına hangi örnekler verilebilir? Bu alanlar ne tür kullanım amaçlarını içerir?")

query("İmar planı paftalarında yer alan plan notlarının hukuki bağlayıcılığı nedir? Plan notları imar uygulamalarında ne gibi bir rol oynar?")
query("Bir arsa sahibi, imar planında yol olarak görülen kısımlarını 'yol terki' yaparsa, bunun anlamı nedir? Bu işlem arsa ve plan açısından neyi ifade eder?")
query("İmar planında bir bölgenin bina yüksekliği 'serbest' olarak belirlenmişse, bu ne anlama gelir? Bina yüksekliği pratikte neye göre sınırlandırılır?")
query("TAKS (taban alanı katsayısı) nedir? Yüksek bir TAKS değeri ile düşük bir TAKS değerine sahip olmak, bir parseldeki yapılaşmanın şeklini nasıl etkiler?")
query("Bir inşaat projesinde fenni mesuliyet kimler tarafından üstlenilir? Fenni mesul olarak görev yapan kişilerin sorumlulukları nelerdir?")

query("Köy yerleşik alanının sınırları nasıl belirlenir ve resmi olarak kim tarafından onaylanır?")
query("Belediyelerin 5 yıllık imar programı nedir? İmar programına alınmayan, kamu hizmetine ayrılmış arsalar için arsa sahipleri yönünden ne gibi sonuçlar doğurur?")
query("Onaylanmış bir imar planına karşı bir vatandaş nasıl itiraz edebilir veya dava açabilir? Plan değişikliğine itiraz ve yargı süreci nasıldır?")
query("Mücavir alan nedir? Bir belediyenin mücavir alan ilan etmesinin amacı nedir?")
query("Belediye ve mücavir alan sınırları dışında kalan yerlerde imar planı yapma ve yapı ruhsatı verme yetkisi hangi kuruma aittir?")